apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opensearch-playground
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: opensearch
                - appName: opensearch-dashboards
          - git:
              repoURL: https://github.com/ruanyl/osd-dev-env.git
              revision: main
              files:
                - path: "playgrounds/**/config.json"

  template:
    metadata:
      name: "{{.appName}}-{{.path.basename}}"
      annotations:
        owner: "{{.owner}}"
        notifications.argoproj.io/subscribe.on-deployed.slack_webhook: ""
        notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook: ""
        notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook: ""
        notifications.argoproj.io/subscribe.on-deleted.slack_webhook_deleted: ""
    spec:
      project: default
      source:
        repoURL: https://github.com/ruanyl/osd-dev-env.git
        targetRevision: main
        path: "charts/{{.appName}}"
        plugin:
          name: helm-argocd-vault-replacer
          env:
            - name: VALUE_FILES
              value: "../../playgrounds/{{.path.basename}}/{{.appName}}.yaml"
      destination:
        name: '{{default "in-cluster" .cluster.name}}'
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
