{{- if .Values.sampleData.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: sample-data-secret
type: Opaque
data:
  SAMPLE_DATA_USERNAME: YWRtaW4=
  SAMPLE_DATA_PASSWORD: <secret:/app/data/opensearch/internal_users~admin|base64>
  SAMPLE_DATA_HOST: b3BlbnNlYXJjaC1jbHVzdGVyLW1hc3Rlcg==
{{- end }}
